#define NO_SYS 1
#define LWIP_IPV4 1
#define LWIP_IPV6 0
#define LWIP_TCP 1
#define LWIP_UDP 0
#define LWIP_RAW 0
#define LWIP_SOCKET 0
#define LWIP_NETCONN 0
#define LWIP_DNS 0
#define LWIP_DHCP 0
#define LWIP_AUTOIP 0
#define LWIP_IGMP 0
#define LWIP_ETHERNET 0
#define LWIP_ARP 0
#define IP_REASSEMBLY 0
#define IP_FRAG 0
#define LWIP_TIMERS 0
#define LWIP_STATS 0
#define MEM_SIZE (32*1024)
#define TCP_MSS 1460
#define TCP_SND_BUF (4*TCP_MSS)
#define TCP_WND (4*TCP_MSS)
#define TCP_OVERSIZE 0
#define LWIP_CHECKSUM_ON_COPY 0
#define SYS_LIGHTWEIGHT_PROT 0
#define LWIP_TCP_TIMESTAMPS 0
#define LWIP_WND_SCALE 0
